image:
  file: .gitpod/Dockerfile

tasks:
  - init: npm install

gitConfig:
  pull.rebase: "true"
  rebase.autoStash: "true"
  core.pager: "diff-so-fancy | less --tabs=4 -RFX"

vscode:
  extensions:
    - "dbaeumer.vscode-eslint"
    - "eamodio.gitlens"
    - "esbenp.prettier-vscode"
    - "redhat.vscode-yaml"
    - "streetsidesoftware.code-spell-checker"
